[package]
name = "dsf-iot"
version = "0.1.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.104"
structopt = "0.3.8"
humantime = "2.0.0"
futures = "0.3.1"
async-std = "1.4.0"
tracing = "0.1.12"
tracing-subscriber = "0.1.6"
bytes = "0.5.4"
chrono-english = "0.1.4"
chrono = "0.4.10"
byteorder = "1.3.4"

[dependencies.dsf-core]
version = "0.1.0"

[dependencies.dsf-rpc]
version = "0.1.0"

[dependencies.dsf-client]
version = "0.1.0"
